require 'rubygems'
require 'bundler/setup'
require 'active_record'
require 'nokogiri'
require 'optparse'
require $PATH + 'config/application'
require $PATH + 'app/helpers/xml_helper'
require $PATH + 'app/controllers/upload_controller'
require $PATH + 'app/controllers/cancel_controller'
require $PATH + 'app/models/concepto'
require $PATH + 'app/models/comprobante'
require $PATH + 'app/models/emisor'
require $PATH + 'app/models/receptor'
require $PATH + 'app/models/timbre_fiscal_digital'
require $PATH + 'app/models/producto'
require $PATH + 'app/models/impuesto'
require $PATH + 'app/models/informancion_aduanera'
require $PATH + 'app/models/domicilio'
require $PATH + 'app/models/traslado'

